# wayfair
brew 'php@7.2'
brew 'composer'
brew 'antigen'
# brew 'getantibody/tap/antibody' # requires > xcode 10.0
brew 'kubernetes-cli'
brew 'kubernetes-helm'
cask 'docker'
cask 'azure-data-studio'
cask 'jetbrains-toolbox'
cask 'rescuetime'
cask 'activitywatch'

# kafka
tap "adoptopenjdk/openjdk"
cask 'adoptopenjdk8'
brew 'kafka'
