brew 'git'
brew 'wget'
brew 'yarn', args: ['without-node']
brew 'nvm'
brew 'ffmpeg' # for youtube-dl's audio conversions
brew 'youtube-dl'
brew 'python' # py3 for aws.sh
brew 'mongodb'

# android
brew 'scrcpy'
cask 'android-platform-tools'

cask 'db-browser-for-sqlite'
cask 'visual-studio-code'
cask 'flux'
cask 'google-chrome'
cask 'firefox'
cask 'postman'
cask 'spectacle'
cask 'clipy'
mas 'Slack', id: 803453959
mas 'The Unarchiver', id: 425424353
